# Generated by Django 3.0.3 on 2020-02-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('datasource', models.CharField(max_length=128)),
                ('campaign', models.CharField(max_length=128)),
                ('clicks', models.PositiveIntegerField()),
                ('impressions', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('date', 'datasource', 'campaign')},
            },
        ),
    ]
